# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mohd Hasnain
title: Cloud Solution Architect
email: mohd-hasnain@outlook.com
#phone: +60 - 16 638 5810 

# Dark Mode (true/false/never)
darkmode: never

# Social links
linkedin_username: mohd-hasnain
github_username:  mohd-hasnain

# Additional icon links
additional_links:
- title: blog
  icon: fa-blogger
  url: https://voidio.blogspot.com/
- title: cclaim
  icon: fa-microsoft
  url: https://www.youracclaim.com/users/mohd-hasnain/

# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/mohd.png
about_content: | # this will include new lines to allow paragraphs  
  Over a decade of experience as a **Solution Architect** for infrastructure and all types of data (big, small, fast, semi-structured, etc. ), 
  including significant consulting experience and strategic advisory with enterprise customers on the **Azure**, **AWS**, 
  **Cloudera**, **Hortonworks**, **Snowflake**, and **Databricks** platforms.
  
  My background includes pre-sales solution architecture to complicated solution execution using a variety of technologies.
  I began my career as a **Database Administrator**. It has helped me grasp the value of data for an organization and has influenced 
  me to improve architectures by combining a variety of skills to deliver the best solutions for managing, handling, and reusing data to 
  produce more and more profit for organizations.
  
  Areas of Expertise
    - **Platform Administration** and **Security** – Hadoop, Linux, Talend, and Cloud
    - **Scalable Data Ingestion** Pipelines – EDW, MDW and ETL
    - **Big Data** ecosystem setup/integration and **Real Time** Data Solution
    
  Recent Activities and Interests
    - **Marathon Runner**
    - **Blogger** - Follow my Technical Blogs at [**VoidIo**](https://voidio.blogspot.com/)
    - **Mentor** - Microsoft Certified [**Trainer**](https://www.youracclaim.com/badges/40d31f64-8811-45ea-8234-0e289b77b9c3/accept), 
    Azure Community [**Hero**](https://enjinx.io/eth/asset/63151533), 
    Azure [**MAPA**](assets/mapa.jpeg)
    - PPG Awarded as [**Star of the Year**](assets/award.jpg) as recognition for the Data Lake projects success

# Projects Section
projects_title: Certifications #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    <mark>BigData</mark> Spark, MapReduce, Kafka, Pig, Oozie, Sqoop, Hue, Impala, Hive, Zookeeper, YARN, Ambari
    
    <mark>Distribution</mark> Databricks, Snowflake, Hadoop, Cloudera, Hortonworks, MapR
    
    <mark>File System</mark> HDFS, DBFS, ADLS, Blob, Avro, Parquet, ORC, Delta
    
    <mark>DevOps</mark> GitHub, Ansible, Jenkins, Maven, Nexus    
    
    <mark>Languages</mark> Python, Scala, Core Java, SQL, Bash

    <mark>RDBMS</mark> MySQL, DB2, Teradata, SQL Server
    
    <mark>NoSQL</mark> OpenTSDB, Hbase, Cassandra, Cosmos DB

    <mark>Security</mark> Kerberos, Ranger, Sentry, AD/LDAP, ACL
    
    <mark>Monitoring</mark> Nagios, Ganglia, PRTG, DataDog

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
