# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mohd Hasnain
title: Cloud Solution Architect – Data & AI
email: mohd-hasnain@outlook.com
phone: +60 - 16 638 5810 

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: mohdhasnain
github_username:  mohd-hasnain

# Additional icon links
additional_links:
- title: blog
  icon: fa-blogger-b
  url: https://voidio.blogspot.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/hasnain.jpg
about_content: | # this will include new lines to allow paragraphs
   Over 10 years of profound experience as **Cloud Solution Architect** for all types of **Data** (Big, Small, Fast, whatever) 
  and **Advanced Analytics** to drive high priority business initiatives on the Microsoft Azure, Cloudera/ Hortonworks and Databricks Platform.
  
  I am highly skilled in: <mark>Azure Cloud</mark> and <mark>Big Data</mark> Frameworks, Solutions and Algorithms with Spark/Hadoop and related technologies.
  
    Started my career with information and data management as Database Administrator.
  It helps me to understand the value and importance of data for any organization.
  It inclined towards improvising current architectures and using skills to use a mixture of various technologies 
  to provide best and optimized solutions which will provide efficient ways to manage, handle and reuse the 
  data to generate more and more profit for organizations
  
  My Specialties:
    - Platform Administration – Hadoop, Linux, Talend and Azure
    - Security - Hadoop and Azure Cloud
    - Big Data ecosystem setup and integration
    - Scalable Ingestion Pipelines – EDW, Modern DW and ETL
    - Real Time Data Solution – Lambda and Delta Architecture
    - Azure DevOps – Infrastructure and Configuration Management
    
  Some of my other interests are:
  
    - **Marathon Runner**
    - **Mentor** - Awarded as **Azure Hero** by Microsoft
    
  Selected recent Accomplishments:
    - Awarded as **Star of the Year** as recognition for the Data Lake success
    - Awarded as ‘Star of the Quarter’ for reducing business impact by 25%
    - Business trip to USA in 2019, have valid B1 visa

# Projects Section
projects_title: Certifications #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    
    <mark>Big Data Technologies</mark> Spark, MapReduce, Flume, Kafka, Storm, Pig, Sqoop, Hue, Tez, Hive, Hcatalog, Azure HDInsight
    
    <mark>Languages</mark> Python, Scala, Java, SQL, Shell Scripting

    <mark>File System</mark> HDFS, DBFS, ADLS, S3, BLOB, SMB file sharing, Sequence files, RCFile, HAR, blob, Avro, Parquet, ORC, Delta

    <mark>Distribution</mark> Cloudera, Hortonworks, MapR, Databricks

    <mark>Workflow Engines</mark> Oozie, Azkban, Luigi, Airflow, Tivoli, Control-M

    <mark>DevOps</mark> Azure DevOps, Git, SVN, TFS, Jenkins, Maven, Nexus

    <mark>RDBMS</mark> MySQL, DB2, Teradata, SQL server, Azure SQL, Azure Synapse
    
    <mark>Orchestration</mark> Talend, Azure Data Factory, Azure Logic Apps

    <mark>NoSQL</mark> OpenTSDB, Hbase, Cassandra, Cosmos DB

    <mark>Security</mark> Kerberos, Ranger, Sentry, TDE, AD/LDAP, ACL, Azure Key Vault

    <mark>Monitoring</mark> Nagios, Ganglia, White Elephant, PRTG, DataDog

    <mark>Cluster Manager</mark> Zookeeper, Mesos, YARN, Ambari, Cloudera Manager

    <mark>BI Tool</mark> DAS, Tableau, Power BI

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
